version: 2

models:
  - name: stg_transactions
    description: Transactions in the Ethereum Bloackchain
    columns:
      - name: hash
        description: >
          This is a ver long section, 
          but however we're going in a good phase
          so, let's see how it goes gng forward
        data_tests:
          - unique
          - not_null
  - name: stg_token_transfers
    description: Token transfers in the Ethereum Blockchain environment
    columns:
      - name: transaction_hash
        description: This is reg the trasaction hash column
        data_tests:
          - not_null
      - name: token_address
        description: Token address is about the tokens where the transaction happened
        data_tests:
          - not_null
  - name: stablecoin_activity_per_day
    latest_version: 2
    config:
      contract:
        enforced: true
        alias_types: true
    columns:
      - name: date
        data_type: date
        description: ""

      - name: token_address
        data_type: varchar
        description: ""

      - name: type
        data_type: varchar
        description: ""

      - name: symbol
        data_type: varchar
        description: ""

      - name: total_usd_value
        data_type: float
        description: ""
    versions:
    
      - v: 1
        deprecation_date: 2030-01-01
        # Matches what's above -- nothing more needed

      - v: 2
        # Removed a column -- this is the breaking change!
        columns:
          # This means: use the 'columns' list from above, but exclude country_name
          - include: all
            exclude: [token_address, symbol]



# sources:
#   - name: eth_schema
#     database: eth
#     tables:
#       - name: contracts
#         columns:
#           - name: address
#             data_type: varchar
#           - name: block_hash
#             data_type: varchar
#           - name: block_number
#             data_type: number
#           - name: block_timestamp
#             data_type: timestamp_ntz
#           - name: bytecode
#             data_type: varchar
#           - name: date
#             data_type: date
#           - name: last_modified
#             data_type: timestamp_ntz

#       - name: token_transfers
#         columns:
#           - name: block_hash
#             data_type: varchar
#           - name: block_number
#             data_type: number
#           - name: block_timestamp
#             data_type: timestamp_ntz
#           - name: date
#             data_type: date
#           - name: from_address
#             data_type: varchar
#           - name: to_address
#             data_type: varchar
#           - name: last_modified
#             data_type: timestamp_ntz
#           - name: log_index
#             data_type: number
#           - name: token_address
#             data_type: varchar
#           - name: transaction_hash
#             data_type: varchar
#           - name: value
#             data_type: float

#       - name: transactions
#         columns:
#           - name: block_hash
#             data_type: varchar
#           - name: block_number
#             data_type: number
#           - name: block_timestamp
#             data_type: timestamp_ntz
#           - name: date
#             data_type: date
#           - name: from_address
#             data_type: varchar
#           - name: gas
#             data_type: number
#           - name: gas_price
#             data_type: varchar
#           - name: hash
#             data_type: varchar
#           - name: input
#             data_type: varchar
#           - name: last_modified
#             data_type: timestamp_ntz
#           - name: max_fee_per_gas
#             data_type: varchar
#           - name: max_priority_fee_per_gas
#             data_type: varchar
#           - name: nonce
#             data_type: varchar
#           - name: receipt_contract_address
#             data_type: varchar
#           - name: receipt_cumulative_gas_used
#             data_type: number
#           - name: receipt_effective_gas_price
#             data_type: varchar
#           - name: receipt_gas_used
#             data_type: number
#           - name: receipt_status
#             data_type: number
#           - name: to_address
#             data_type: varchar
#           - name: transaction_index
#             data_type: number
#           - name: transaction_type
#             data_type: number
#           - name: value
#             data_type: float
